### ISSUE TITLE
Unclear install instructions

### ISSUE THREAD

**Issue by derickito** [Rarst/wps#10]
Where are you supposed to install this? The plugin folder? Is not clear in the install instructions

**Comment by Rarst** [comment]
The preferred installation is with Composer dependency manager.

You can also download release archive and install it manually as a regular WordPress plugin, [through admin or FTP upload](https://codex.wordpress.org/Managing_Plugins#Manual_Plugin_Installation).

Does this answer your question?

**Comment by derickito** [comment]
Yes. I saw the composer command I just didn’t know where to execute it. Thanks.

**Comment by arnisjuraga** [comment]
And where is it? Please, share the instructions. They are unclear in the readme indeed.

**Comment by Rarst** [comment]
Readme links to general Composer documentation for its use, the concepts are somewhat too extensive to re-explain in a limited space. :)

If you are not using Composer, you might prefer to download and use linked zip release and install it as regular plugin, as above.

**Comment by arnisjuraga** [comment]
I am using composer. 
As usually, I go to Wordpress root and run composer isntall, that will do nothing. :)

**Comment by Rarst** [comment]
Ah, if you do, you have two options then:

1. If you use Composer for your entire site `composer require rarst/wps` in that install's root will add the plugin to project. It will get installed wherever your configuration tells `wordpres-plugin` type packages to go.
2. If you want to install plugin separately by itself `composer create-project rarst/wps` would do that wherever you want (probably plugins directory). Result will be roughly equivalent to provided zip archive.

**Comment by arnisjuraga** [comment]
This is great plugin and easy way to enable Whoops, but ... tiny little more instructions on the install would be great for developers and users not familiar with composer. And I believe, majority of Wordpress users and developers are not.

Few more simple notes after tests:
* Wordpress is not loading composer packages by default. Although running `composer require` from Wordpress root will copy plugin to plugins directory, it will not be possible to "Activate" it because `wps.php` tries to load composer packages from plugins directory, which are not available there if installed from root. So You need to configure composer autoload somewhere.

* If You "load" composer in `functions.php` - You still will not be able to activate plugin, because Plugins are loaded before `functions.php`. So, this requires some additional configuration.

* You could recommend, either to add it to `wp-load.php` or `wp-config.php`?
```require_once __DIR__ . "/vendor/autoload.php";```

or by changing plugin itself?:
```php
if(file_exists(__DIR__ . "/../../../vendor/autoload.php"){
        require_once __DIR__ . "/../../../vendor/autoload.php";
}elseif ( file_exists( __DIR__ . '/vendor/autoload.php' ) ) {
        require __DIR__ . '/vendor/autoload.php';
}

```

* And, of course, again the step to set in `wp-config.php`
```php
define( 'WP_DEBUG', true );
define( 'WP_DEBUG_DISPLAY', true );
```

**Comment by Rarst** [comment]
Appreciate the input!

For the record I have literally entire site explaining Composer to WP folks https://composer.rarst.net/ so I am not dismissive of the knowledge issue. :)

But as above, this is extensive and nuanced chunk of information, that I am not looking to include (and maintain!) in every single readme.

**Comment by arnisjuraga** [comment]
This is great page! But still - after 3 clicks and 1 minute of reading, I did not find an example `how to correctly include composer autoload.php` into Wordpress core. Understand me correctly- I _am_ able to do that myself, but better not skip such simple "it's obvious!" instructions. They can really help for beginners and takes only 2 lines of code for instruction author.

**Comment by Rarst** [comment]
My point that is not _simple_ instruction at all. Coming from vanilla WordPress it introduces _a lot_ of concepts that require a lot of explanation.

Directing to Composer documentation is what works for me at the moment.
