### ISSUE TITLE
REST API?

### ISSUE THREAD

**Issue by k1sul1** [Rarst/wps#5]
It seems that REST API serves the full pretty error page whenever there's an error, which is a bit bad when you're expecting JSON. 

I looked into the source, and tried replacing DOING_AJAX constants with REST_REQUEST, but that didn't do anything noticeable. Am I missing something maybe?

**Comment by Rarst** [comment]
Need to look into, hadn't dealt with REST API. Probably needs a new handler added for it like `Admin_Ajax_Handler` one.

**Comment by Rarst** [comment]
Could you please try this in your case and confirm its good to go into next release? :)

**Comment by k1sul1** [comment]
Sure thing, first thing tomorrow!

**Comment by k1sul1** [comment]
It still gives me the pretty error page for whatever reason, any idea on how to debug?

![image](https://user-images.githubusercontent.com/2719615/32093195-24af3706-bb04-11e7-98d9-b394ae219be5.png)

**Comment by Rarst** [comment]
I think the problem is that your error happens early in core load.

The difference with `DOING_AJAX` is that admin ajax is a separate dedicated endpoint and constant is defined _very_ early. But REST API is "virtual", `REST_REQUEST` is defined way way later in the process on `parse_request` hook. Anything before that wouldn't "know" it is a REST API context specifically.

I will think some more, but I don't see a clean way to detect it early so far.

**Comment by Rarst** [comment]
Ok, I added some dirty detection for early cases, try this time, please? :)

**Comment by k1sul1** [comment]
That seems to have done the trick! Thank you for your great work :) 

I don't think that your solution is dirty, it's a necessary evil, as errors tend to appear in strange places and just about any error breaks the JSON response.

**Comment by gmazzap** [comment]
@Rarst yes, checking the URL is the only way to early detect REST API.

But df97a75 has some issues:

- `$_SERVER['REQUEST_URI']` is a bit problematic because on some setups it might returns the full URL and not just the path.
- You can't check just the REST prefix. In a setup where _home_ URL is `example.com/subdir` your condition will fail because `$_SERVER['REQUEST_URI']` will be something like `subdir/wp-json` so REST prefix (`wp-json`) is not at the start of `$_SERVER['REQUEST_URI']`. So you would need to check the REST _URL_ but that's problematic because rewrites might not be available yet...

This is a solution copied and pasted from a project of mine:

```php
function is_rest_request() {

	if ( defined( 'REST_REQUEST' ) && REST_REQUEST ) {
		return true;
	}

	if ( get_option( 'permalink_structure' ) && empty( $GLOBALS[ 'wp_rewrite' ] ) ) {
		/*
		 * Rewrites are used, but it's too early for global rewrites be there.
		 * Let's instantiate it, or `get_rest_url()` will fail.
		 * This is exactly how WP does it, so it will do nothing bad. In worst case, WP will override it.
		 */
		$GLOBALS[ 'wp_rewrite' ] = new \WP_Rewrite();
	}

	$current_path  = (string) parse_url( add_query_arg( [] ), PHP_URL_PATH );
	$rest_url_path = (string) parse_url( get_rest_url(), PHP_URL_PATH );

	return apply_filters( 'wps_is_rest_early', strpos( $current_path, $rest_url_path ) === 0 );
}
```

_Still_ dirty, even more dirty, but also a little bit more reliable.

**Comment by Rarst** [comment]
I am not checking for the _start_, just that it's in there somewhere. I think for a _debug_ tool this is kinda sorta good enough. It will be _occasional_ false positive, but it will work _usually_ for REST requests.

Taking note of your solution, but I am absolutely not touching rewrite anything for this case. Not worth it. :)

**Comment by gmazzap** [comment]
mmm I think `0 !== stripos( $_SERVER['REQUEST_URI'], rest_get_url_prefix() )` is always true (because URI starts with `/` )?

It should be maybe `false !== stripos( $_SERVER['REQUEST_URI'], rest_get_url_prefix() )`.

I'm not really _touching_ rewrites, just defining the global, that is accessed in the rest url function without check for existence.

**Comment by Rarst** [comment]
I corrected that to `false` already :D Though `0` de facto worked since there is appended slash so it didn't match at start.
